# Generated by Django 3.2.2 on 2021-05-23 14:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music_world', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='date_posted',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
