# Generated by Django 3.2.2 on 2021-05-13 15:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_world', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='events_time',
            new_name='events_date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='events_date',
        ),
    ]
