# Generated by Django 3.2.2 on 2021-05-13 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_world', '0002_auto_20210513_2340'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='tittle',
            new_name='title',
        ),
    ]
