# Generated by Django 3.2.2 on 2021-05-17 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_world', '0004_auto_20210517_2344'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='category',
            new_name='categories',
        ),
    ]
