# Generated by Django 3.2.2 on 2021-05-15 16:51

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('music_world', '0003_rename_tittle_event_title'),
        ('reviews', '0002_review_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='event',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='music_world.event'),
            preserve_default=False,
        ),
    ]
